// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6CMW0fuxIHRmmWm13KIyVOpZgS1LNKrM',
    appId: '1:146228195760:web:078f0f9fc8c2d2be8d6675',
    messagingSenderId: '146228195760',
    projectId: 'chatapptute-94ddd',
    authDomain: 'chatapptute-94ddd.firebaseapp.com',
    storageBucket: 'chatapptute-94ddd.appspot.com',
    measurementId: 'G-RH0RG7YWYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnTNEkhEIWz5Ju194xaINacQbkekLLSfM',
    appId: '1:146228195760:android:10fb12964260ae398d6675',
    messagingSenderId: '146228195760',
    projectId: 'chatapptute-94ddd',
    storageBucket: 'chatapptute-94ddd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfs2ojqWMVwEIr4hjrBJkJqPWzNB9XfOA',
    appId: '1:146228195760:ios:aad44c2aff7a978a8d6675',
    messagingSenderId: '146228195760',
    projectId: 'chatapptute-94ddd',
    storageBucket: 'chatapptute-94ddd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfs2ojqWMVwEIr4hjrBJkJqPWzNB9XfOA',
    appId: '1:146228195760:ios:e4853be936bf2f718d6675',
    messagingSenderId: '146228195760',
    projectId: 'chatapptute-94ddd',
    storageBucket: 'chatapptute-94ddd.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
